POST http://localhost:3000/signup
Content-Type: application/json

{
    "firstName": "neji",
    "lastName": "Hyuga",
    "role": "Software dev",
    "email": "neji@gmail.com",
    "password": "Password@1"
}

###

POST http://localhost:3000/signin
Content-Type: application/json

{
    "email": "neji@gmail.com",
    "password": "Password@1"
}